### ISSUE TITLE
Add support for the network volume

### ISSUE THREAD

**Issue by TimPietrusky** [blib-la/runpod-worker-comfy#1]
In order to let the user add custom things (like models / LoRA / nodes) into Comfy without changing the actual docker image, we could leverage a [network volume](https://docs.runpod.io/docs/create-a-network-volume).

**Comment by kenster4000** [comment]
yes please :)

**Comment by TimPietrusky** [comment]
This will propably come next week as we also need this feature!

**Comment by ardha27** [comment]
is this already implemented?

> This will propably come next week as we also need this feature!

**Comment by TimPietrusky** [comment]
@ardha27 sadly, we had a change in plans and couldn't implement it yet. But we want to do this, we just can't promise a deadline. 

Overall, this feature will not very complicated, it's mostly split into to parts:

1. Configure the network volume on RunPod and how to prepare it to be used with runpod-worker-comfy
2. Mount the network volume into the container, so that the network-volume is used instead of the folders in ComfyUI

**Comment by agawrylak** [comment]
how exactly do i set the container to use the network volume? @TimPietrusky

**Comment by TimPietrusky** [comment]
@kenster4000 @ardha27 support for network-volumes is finally merged! 

Thanks to @Meptl for helping out.
