### ISSUE TITLE
[BUG]: Missing Github Actions

### ISSUE THREAD

**Issue by brgrp** [blib-la/runpod-worker-comfy#25]
Hi, I read the documentation and realized that the files [docker-dev.yml](https://github.com/blib-la/runpod-worker-comfy/blob/main/.github/workflows/docker-dev.yml) [docker-release.yml](https://github.com/blib-la/runpod-worker-comfy/blob/main/.github/workflows/docker-release.yml) as mentioned in the readme do not exists.

I would be pleased if you could add them.
Thank you

**Comment by TimPietrusky** [comment]
@brgrp thanks for reporting this. 

You are right, we renamed the workflows and forgot to update the README. You can find them here: https://github.com/blib-la/runpod-worker-comfy/tree/main/.github/workflows
