### ISSUE TITLE
Access the WebUI

### ISSUE THREAD

**Issue by crax0** [blib-la/runpod-worker-comfy#26]
**Is your feature request related to a problem? Please describe.**

Im trying to access the WebUI somehow.. 

**Describe the solution you'd like**

Im already building my own image from the dev brach and can connect the network storage for my own models but is there any way to access the WebUi of the running serverless instance? Maybe someone could tell me what i have to do to access it. Expose the port 8188 in the Dockerfile and map it in runpod?

**Comment by brgrp** [comment]
Add --listen to start.sh

`python3 /comfyui/main.py --disable-auto-launch --disable-metadata --listen &`

**Comment by crax0** [comment]
Thanks for the reply! If i add --listen, where do i find the full url for the webui to access it? Since the script only exports api routes on a serverless instance 🤔

**Comment by crax0** [comment]
Any ideas? @brgrp

**Comment by maxabrahamsson** [comment]
Hi @crax0 ,

I am stuck with the same issue, were you able to find a way to access the webui after adding the --listen parameter?

Thanks!

**Comment by crax0** [comment]
Unfortunately not 👎🏼 
Still looking for a way to access it...

**Comment by brgrp** [comment]
Ah, I see, why would you want to get web interface access for a serverless instance?
That doesn't make sense to me as serverless only works when you send a request.

You can also use the docker image on a pod instance and that should work as suggested.
I'm not sure if serverless instances provide a public URL.
Thats probably a question for runpod.

**Comment by TimPietrusky** [comment]
@crax0 @brgrp @maxabrahamsson we added this directly into the worker: [Access ComfyUI via WebUI](https://github.com/blib-la/runpod-worker-comfy?tab=readme-ov-file#local-api).
