### ISSUE TITLE
Execution time can't be increased

### ISSUE THREAD

**Issue by Tallisgo** [blib-la/runpod-worker-comfy#31]
**Describe the bug**
I excute test_input.json need 7s， but I excute sdxl json need 59s.

![image](https://github.com/blib-la/runpod-worker-comfy/assets/55240330/49e9e40b-b4f3-446a-99be-f0963020c3a8)

Can you please provide me some solutions to find the reasons.

**Comment by TimPietrusky** [comment]
@Tallisgo we will make the execution time configurable, then you can just do this via environment-variables.

**Comment by TimPietrusky** [comment]
@Tallisgo you can now [configure the execution time via env variables](https://github.com/blib-la/runpod-worker-comfy?tab=readme-ov-file#config).
