### ISSUE TITLE
Minimal Docker Image

### ISSUE THREAD

**Issue by ecornbower** [blib-la/runpod-worker-comfy#41]
It would be nice to have a pre-built Docker image that does not contain the default models, e.g. built using `SKIP_DEFAULT_MODELS=1`.

We're using a network volume to store models so we don't need the models baked into the image.

Perhaps it could be tagged as `{version}-minimal` or similar.

**Comment by TimPietrusky** [comment]
@ecornbower we updated the build process and do provide 3 different images now:

  - `timpietruskyblibla/runpod-worker-comfy:3.0.0-base`: doesn't contain any checkpoints, just a clean ComfyUI image
  - `timpietruskyblibla/runpod-worker-comfy:3.0.0-sdxl`: contains the checkpoints and VAE for Stable Diffusion XL
  - `timpietruskyblibla/runpod-worker-comfy:3.0.0-sd3`: contains the medium checkpoint for Stable Diffusion 3

So the one you are looking for is `<version>-base`! 

Please let us know if this is working for you.

**Comment by ecornbower** [comment]
@TimPietrusky Awesome, thanks so much!

**Comment by TimPietrusky** [comment]
@ecornbower you are super welcome!
