### ISSUE TITLE
Couldn't load the base docker image with custom model in network mounted drive

### ISSUE THREAD

**Issue by dannykok** [blib-la/runpod-worker-comfy#54]
I was trying to run a clean comfy instance with custom models and nodes. So I tried setting up the serverless endpoint using `timpietruskyblibla/runpod-worker-comfy:3.0.0-base` docker image, however it just kept starting and killed prematurely without taking any job, while using `timpietruskyblibla/runpod-worker-comfy:3.0.0-sdxl` works fine. 

I think it's okay to use the sdxl one, just I am not quite understand why it is.

I am sorry if this is odd since I am still new to Comfy. Any help is appreciated.

**Comment by TimPietrusky** [comment]
@dannykok thanks for reporting this. We will check this bug and then come back to you!

**Comment by hoblin** [comment]
I had the same issue. Fixed by creating model directories before models download
```
# Create necessary directories
RUN mkdir -p models/checkpoints models/vae

```
(In case `MODEL_TYPE` is not set, the `COPY` command doesn't have a directories to copy.

**Comment by TimPietrusky** [comment]
@hoblin awesome, thank you! Do you mind to create a PR for this fix? That would help us a lot! 🙏
