### ISSUE TITLE
Support FLUX.1

### ISSUE THREAD

**Issue by TimPietrusky** [blib-la/runpod-worker-comfy#55]
**Is your feature request related to a problem? Please describe.**

I want to use FLUX.1 via an API. 

**Describe the solution you'd like**

I have an image that already contains the models needed to run FLUX.1. 

**Describe alternatives you've considered**

Forking this repo and creating the image myself.

**Comment by 2-fly-4-ai** [comment]
Hey Tim, Could you add an example input to the repo for running the Flux version.
