### ISSUE TITLE
Allow images or files input via file urls

### ISSUE THREAD

**Issue by dannykok** [blib-la/runpod-worker-comfy#57]
I am working on a feature to allow input of files by specifying the URL of the files in the input payload.

Currently, we upload the image using base64 encoding, which they are then serialized through the job dispatching of runpod serverless. However, runpod currently has a [limitation on the payload size of 10MB](https://docs.runpod.io/serverless/references/operations), which prohibits large file input. One way to solve is to instead use remote file URLs in the input payload, and the `rp_handler` will download the files and re-upload to the Comfy server.

Just to see if you would love this idea, which I could submit a PR later.

**Comment by jelling** [comment]
You should be able to do this already without needing this repo to make any changes. When passing the workflow definition, use a node like `LoadImagesFromUrl` and pass in the image URLs you want as input params.

**Comment by dannykok** [comment]
> You should be able to do this already without needing this repo to make any changes. When passing the workflow definition, use a node like `LoadImagesFromUrl` and pass in the image URLs you want as input params.

Yes you are right. Actually most stuff could be done with nodes.
