### ISSUE TITLE
model / custom node provisioning script

### ISSUE THREAD

**Issue by Dekita** [blib-la/runpod-worker-comfy#6]
If we could somehow define a 'provisioning' type script that allows for custom models etc to be added to the container image that'd be great! I seem to be having severe issues when trying to manually re-create the image locally :( 

Perhaps something similar to the ai-dock runpod images (which is set via an env variable pointing to a github url where the prov script is, see the docker-compose for the project): 
https://github.com/ai-dock/comfyui/tree/main/config/provisioning

edit: not really sure if this is possible for during the image build step, might still need to rebuild the image for custom models, but it'd be nice! :D

**Comment by TimPietrusky** [comment]
@Dekita It might be a good idea to introduce the [network-volume](https://docs.runpod.io/docs/create-a-network-volume) for this case and connect this with Comfy, so that you can put any model you want into the volume and then those will be used instead of the ones that come with the image. 

How does this sound?

**Comment by Dekita** [comment]
yea that sounds like it could work fine. end goal is just to be able to use custom models/loras/workflow nodes etc :)

**Comment by TimPietrusky** [comment]
@Dekita then I will continue the work in #1 and if it works fine, we can close this one, ok?

**Comment by Dekita** [comment]
yea thats fair, a network volume would likely help a lot for keeping the image size small too :)

**Comment by TimPietrusky** [comment]
@Dekita thank you so much for all your input! 

* We decided to not provide a custom provisioning script, but keep it simple. 
* The network-volume was implemented with [2.2.0](https://github.com/blib-la/runpod-worker-comfy/releases/tag/2.2.0).
