### ISSUE TITLE
👋 Help me fix the Response Error?

### ISSUE THREAD

**Issue by ajithradnus** [blib-la/runpod-worker-comfy#68]
Hi,

### Do you know why I'm receiving this response
**"error": "Error waiting for image generation: '<' not supported between instances of 'int' and 'str'",**

![image](https://github.com/user-attachments/assets/5a777368-9373-4da9-9d38-e98c6e2ecdff)

### The prompt ran smoothly in the Runpod log, but the output response failed. Can you help me figure out how to fix this?

![image](https://github.com/user-attachments/assets/e26c809a-5ef2-4f2d-acf6-becf5ffd2b22)

![image](https://github.com/user-attachments/assets/5c159486-19a8-45b8-9717-4daf7562cd86)

### My Environment variables
![image](https://github.com/user-attachments/assets/b646292a-4ca9-48de-9287-27836d920056)

best
Radnus

**Comment by ajithradnus** [comment]
Do I need to add any more environment variables?

![image](https://github.com/user-attachments/assets/791cbfe8-8364-4af1-8c7a-6dea3c073edb)

**Comment by Pseudotools** [comment]
This looks like a small bug where the environment variables COMFY_POLLING_MAX_RETRIES and COMFY_POLLING_INTERVAL_MS have not been converted from string to int. Am testing to confirm now. Try removing these environment variables from your template.

**Comment by Pseudotools** [comment]
Submitted pull request to fix:
https://github.com/blib-la/runpod-worker-comfy/pull/70

**Comment by ajithradnus** [comment]
Thanks 👍
