### ISSUE TITLE
provide image input for api

### ISSUE THREAD

**Issue by Satttoshi** [blib-la/runpod-worker-comfy#7]
**User Story:**
As a user,

**Description:**
I want the ability to utilize custom images within img2img, controlnet, or any other feature that requires an input image. This way, I can dynamically populate an image-loader node.

**Current Limitation:**
Currently, the only way to use images is through the workflow as a request. If I require an image for the image-loader node, I'm forced to include it into the comfyui image input directory (./comfy/input).

**Enhancement Request:**
It would be highly beneficial if there were optional fetching variables available for the handler. These variables should allow the handler to accept a Base64-encoded PNG image along with its name (e.g., egg.png). This image can then be used seamlessly within the image-loader node.

**Comment by TimPietrusky** [comment]
@Satttoshi that sounds totally reasonable. Maybe we would actually allow multiple input images, so like an array? 

We just have to take into account, that the payload size limit is 10 MB for `run` and 20 MB for `runsync`. So it might also be a good idea to upload the images to an external storage and provide the URL instead of the base64 version. 

What do you think?

**Comment by Satttoshi** [comment]
Hey @TimPietrusky 

usually there is not more than one or two input images needed. In regard of request-size that is reasonable. I think providing a link would be the best here, but I would love to see both options. The handler coule just check for either its b64 or link and resolve around this.

**Comment by ckao10301** [comment]
Hi @TimPietrusky, any updates on this? I'm looking forward to this feature too. I think image input as URL is best for most applications. A workflow with image to image, 1 controlnet, faceswap, would use 3 input images, so multiple input images would be necessary.

**Comment by TimPietrusky** [comment]
@ckao10301 it's already implemented and tested in one of our projects. Will provide a release later today!

**Comment by ckao10301** [comment]
You're awesome, looking forward to it!

**Comment by menguzat** [comment]
I can't seem to get a handle on this.
I upload the image in images, use LoadImage node in the workflow with the file name (just the file name, no path) but get "image not found" error.

how to properly use this? it would be nice if you could provide example workflows and api calls with images too...
